Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-18.04"
  c.vm.box_url = "https://vagrantcloud.com/bento/ubuntu-18.04"
  c.vm.hostname = "default-ubuntu-1804.vagrantup.com"
  c.vm.network(:private_network, {:ip=>"192.168.33.50"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "C:/Users/nick.howell/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-puppet-foldingathome-default-ubuntu-1804-210e121b-e115-4c73-a2aa-f676131f9a03"
    p.customize ["modifyvm", :id, "--audio", "none"]
    p.customize ["modifyvm", :id, "--cpus", "2"]
    p.customize ["modifyvm", :id, "--memory", "4096"]
  end
end
